---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
git_enablerepo: ""
git_packages:
  - git
git_global_config_user_name: "pam79"
git_global_config_user_email: "paapaabdullahm@gmail.com"
git_global_config_core_editor: "vim"
git_global_config_branch_autosetuprebase: "always"
git_global_config_push_default: "current"
aptcachetime: 3600
locale: "en_GB.UTF-8"
timezone: "Africa/Accra"
desktop_autostart:
  add:
    - { name: Tilda , exec: /usr/bin/tilda }
  remove:
    - deja-dup-monitor.desktop
    - onboard-autostart.desktop
    - orca-autostart.desktop
    - vino-server.desktop
php_phar_tools:
  php_cs_fixer: true
  phpcpd: true
  sami: true
  robo: true
  phpmd: true
  phpunit: true
  codeception: true
  cssprites: true
  wpcli: true
ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
vhosts:
  - template: standard
    vhost: "default70.dev"
    path: "{{ ansible_env.HOME }}/projects/default-7.0"
  - template: standard
    vhost: "default56.dev"
    path: "{{ ansible_env.HOME }}/projects/default-5.6"
    php: "5.6"