---

- name: Install GNOME 3 desktop packages
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: yes
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  with_items:
    - gnomeshell
    - ubuntu-gnome-desktop
  register: gnome3_install
  notify:
    - Set User XSession to GNOME 3
