---

- name: Add Numix Icon Theme PPA repository
  apt_repository:
    repo: 'ppa:numix/ppa'
    state: present

- name: Add Papirus Icon Theme PPA repository
  apt_repository:
    repo: 'ppa:papirus/papirus'
    state: present

- name: Install GNOME 3 desktop packages
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: yes
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  with_items:
    - gnome-shell
    - ubuntu-gnome-desktop
  register: gnome3_desktop_install

- name: Set User XSession to GNOME 3
  become: false
  raw: python xsession.py --user-name {{ ansible_env.USER }} set gdm3
  when: gnome3_desktop_install is changed

- name: Set Window Buttons back to left
  become: false
  raw: gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'
  when: gnome3_desktop_install is changed

- name: Install GNOME 3 Icon Theme packages
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: yes
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  with_items:
    - numix-gtk-theme
    - numix-icon-theme-circle
    - papirus-icon-theme
  register: gnome3_icon_theme_install

- name: Install GNOME 3 extensions
  raw: bash gnome3-extension.sh -s -i --eid {{ item.id }} -v latest
  with_items:
    - { name: "Activities Configurator", id: 358 }
    - { name: "Workspace to Dock", id: 427 }
    - { name: "Dash to Dock", id: 307 }
    - { name: "Dash to Panel", id: 1160 }
    - { name: "OpenWeather", id: 750 }
    - { name: "Extensions", id: 1036 }
    - { name: "Sound Input & Output Device Chooser", id: 906 }
    - { name: "Workspace Indicator", id: 21 }
    - { name: "Pomodoro", id: 53 }
    - { name: "Gravatar", id: 1015 }
  when: gnome3_desktop_install is succeeded
