---

# - import_tasks: configure-license.yml

- import_tasks: configure-disabled-plugins.yml

- import_tasks: configure-jdk-table.yml

- import_tasks: configure-project-defaults.yml

- import_tasks: install-code-styles.yml

- import_tasks: configure-code-style.yml
