---

- name: Import Wavebox PGP Apt signing key
  apt_key:
    url: https://wavebox.io/dl/client/repo/archive.key
    state: present

- name: Add Wavebox x86_64 repository
  apt_repository:
    repo: 'deb https://wavebox.io/dl/client/repo/ x86_64/'
    state: present
  when:
    - ansible_architecture == 'x86_64'

- name: Install Wavebox
  apt: pkg=wavebox state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  register: wavebox_install

- name: Set Wavebox launcher icon
  become: false
  raw: python launcher_add.py wavebox.desktop 3
  when: wavebox_install is succeeded
