---

- name: Create XDM download directory
  file:
    dest: "{{ ansible_env.HOME }}/.xdm/archives"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Create XDM staging directory
  file:
    dest: "{{ ansible_env.HOME }}/.xdm/{{ xdm_version }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Download XDM Tarball
  get_url:
    url: "{{ xdm_base_url }}/{{ xdm_version }}.tar.xz/download"
    dest: "{{ ansible_env.HOME }}/.xdm/archives/{{ xdm_version }}.tar.xz"
  register: xdm_archive

- name: Unarchive XDM Source
  unarchive:
    src: "{{ ansible_env.HOME }}/.xdm/archives/{{ xdm_version }}.tar.xz"
    dest: "{{ ansible_env.HOME }}/.xdm/{{ xdm_version }}/"
    remote_src: yes
  register: xdm_unarchive
  when: xdm_archive is changed

- name: Install XDM
  shell: install.sh
  args:
    chdir: "{{ ansible_env.HOME }}/.xdm/{{ xdm_version }}/"
  when: xdm_unarchive is succeeded
