---

- name: Import Google Chrome GPG signing key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
    id: 7FAC5991

- name: Add Google Chrome x86_64 repository
  apt_repository:
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    state: present
  when: ansible_architecture == 'x86_64'

- name: Install Google Chrome
  apt: pkg=google-chrome-stable state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  register: google_chrome_install

- name: Set Google Chrome launcher icon
  become: false
  raw: python launcher_add.py google-chrome.desktop 3
  when: google_chrome_install is changed

- name: Set Google Chrome as default browser
  become: false
  raw: xdg-settings set default-web-browser google-chrome.desktop
  when: google_chrome_install is changed

- name: Set Google Chrome preferences
  template:
    src: master_preferences.json.j2
    dest: /opt/google/chrome/master_preferences
  register: google_chrome_pref_set
  when: google_chrome_install is changed

- name: Ensure bookmarks.html exists
  stat:
    path: "{{ playbook_dir }}/roles/google-chrome/files/bookmarks.html"
  register: bookmarks

- debug:
    msg: "bookmarks.html is not defined (file doesn't exist)"
  when: not bookmarks.stat.exists

- debug:
    msg: "bookmarks.html is defined (file exist)"
  when: bookmarks.stat.exists is defined and bookmarks.stat.exists

- name: Copy Google Chrome bookmarks file if exists
  copy:
    src: bookmarks.html
    dest: /opt/google/chrome/bookmarks.html
    mode: 0644
  when: bookmarks.stat.exists is defined and bookmarks.stat.exists

- name: Create Google Chrome extensions directory
  file:
    path: /opt/google/chrome/extensions/
    state: directory

- name: Create Google Chrome json file to install extensions
  template:
    src: chrome-extensions.json.j2
    dest: /opt/google/chrome/extensions/{{ item.id }}.json
    mode: 0644
  with_items:
    - name: Adblock Plus
      id: cfhdojbkjhnklbpkdaibdccddilifddb
    - name: Augury
      id: elgalmkoelokbchhkhacckoklkejnhcd
    - name: builtwith-technology-prof
      id: dapjbgnjinbpoindlpdmhochffioedbn
    - name: Care your Eyes
      id: fidmpnedniahpnkeomejhnepmbdamlhl
    - name: Checker Plus for Gmail™
      id: oeopbcgkkoapgobdbedcemjljbihmemj
    - name: Color Picker
      id: iegjhenkjneoaocdnoakkcgfdfcpbede
    - name: Color Picker and Converter
      id: ofkcpbjmhcdipbhcdfechmckpaofdjlf
    - name: ColorPick Eyedropper
      id: ohcpnigalekghcmgcdcenkpelffpdolg
    - name: cookies.txt
      id: njabckikapfpffapmjgojcnbfjonfjfg
    - name: Cookie Inspector
      id: jgbbilmfbammlbbhmmgaagdkbkepnijn
    - name: EverSync
      id: iohcojnlgnfbmjfjfkbhahhmppcggdog
    - name: github-submodule-links
      id: ncoknneddcolmgfnmcbemhhaghjdlkkb
    - name: Grepsr - Web Scraping Tool
      id: hjdijkhlfpeafghibmiabeofkiicdnjm
    - name: isometric-contributions
      id: mjoedlfflcchnleknnceiplgaeoegien
    - name: jsonview
      id: chklaanhfefbnpoihckbnefhakgolnmc
    - name: kimono
      id: deoaddaobnieaecelinfdllcgdehimih
    - name: LinkedIn Extension
      id: meajfmicibjppdgbjfkpdikfjcflabpk
    - name: Mobile/Responsive Web Design Tester
      id: elmekokodcohlommfikpmojheggnbelo
    - name: ModHeader
      id: idgpnmonknjnojddfkpgkljpfnnfcklj
    - name: postman
      id: fhbjgbiflinjbdggehcddcbncdddomop
    - name: Ripple Emulator (Beta)
      id: geelfhphabnejjhdalkjhgipohgpdnoc
    - name: stylish
      id: fjnbnpbmkenffdnngjfgmeleoegfcffe
    - name: TCP Socket debugger
      id: fenhpkaocajfmpchcojgniehkamhkafp
    - name: Video DownloadHelper
      id: lmjnegcaeklhafolokijcfjliaokphfk
    - name: WAVE Evaluation Tool
      id: jbbplnpkjmmeebjpijfedlgcdilocofh
    - name: XDM Browser Monitor
      id: bgpkelneombgembocnickiddlbebmica
    - name: YouTube Downloader
      id: pncidppbibhnmkmhmeoiheclffhpaeac
    - name: Zoom Scheduler
      id: kgjfgplpablkjnlkjmjdecgdpfankdle
