- name: Ubuntu Desktop Configuration
  hosts: localhost
  roles:
    # Common
    - { role: git, become: true }
    - { role: locales, become: true }
    - { role: essentials, become: true }
    - { role: java-openjdk, become: true }
    - { role: google-chrome, become: true }
    - { role: oh-my-zsh, become: true }
