- name: Ubuntu Desktop Configuration
  hosts: localhost
  roles:

    # Common Tools
    - { role: locales, become: true }
    - { role: essentials, become: true }
    - { role: git, become: true }
    - { role: oh-my-zsh, become: true }
    - { role: java-openjdk, become: true }

    # Developer Tools
    - { role: apache-maven, become: true }
    - { role: atom, become: true }
    - { role: dia, become: true }
    - { role: docker, become: true }
    - { role: docker-images, become: true }
    - { role: google-chrome, become: true }
    - { role: jetbrains-idea, become: true }
    - { role: jetbrains-idea-plugins, become: true }
    - { role: smartgit, become: true }
    - { role: sublime, become: true }
    - { role: virtualbox, become: true }
    - { role: vagrant, become: true }
    - { role: kubectl, become: true }
    - { role: minikube, become: true }
    - { role: helm, become: true }

    # Utility Tools
    - { role: brave, become: true }
    - { role: calibre, become: true }
    - { role: gnome-chess, become: true }
    - { role: gnome-tweak-tool, become: true }
    - { role: gnome-user-share, become: true }
    - { role: gnucash, become: true }
    - { role: xdman, become: true }
    - { role: inkscape, become: true }
    - { role: kdenlive, become: true }
    - { role: keepass-xc, become: true }
    - { role: rosegarden, become: true }
    - { role: simple-screen-recorder, become: true }
    - { role: sound-converter, become: true }
    - { role: sound-juicer, become: true }
    - { role: unity-tweak-tool, become: true }
    - { role: woe-usb, become: true }

    # Other Tools
    - { role: clean-apt-entries, become: true }
    - { role: disable-apport, become: true }
    - { role: critical-battery-action, become: true }
    # - { role: customize-ui, become: true }
    # - { role: setup-gnome3-desktop, become: true }
