---

- name: Create Rambox download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ rambox_download_dir }}'

- name: Ensure file exists in download dir
  stat:
    path: "{{ rambox_download_dir }}/{{ rambox_filename_new }}"
  register: download_file

- name: Download Rambox
  get_url:
    url: '{{ rambox_base_url }}/{{ rambox_version_new }}/{{ rambox_filename_new }}'
    dest: '{{ rambox_download_dir }}/{{ rambox_filename_new }}'
    checksum: "sha256:{{ rambox_sha256sum }}"
    timeout: '{{ intellij_idea_download_timeout_seconds }}'
    mode: 'u=rw,go=r'
  register: download_file_new
  when: not download_file.stat.exists

- name: Delete Rambox old installation file
  command: rm -rf {{ rambox_download_dir }}/{{ rambox_filename_old }}
  when: download_file_new is changed

- name: Install Rambox
  apt:
    deb: "{{ rambox_download_dir }}/{{ rambox_filename_new }}"
  register: rambox_install

- name: Set Rambox launcher icon
  become: false
  raw: python launcher_add.py rambox.desktop 3
  when: rambox_install is changed
