---

compose_version: "1.21.0"
compose_base_url: "https://github.com/docker/compose/releases/download"
compose_sha256: af639f5e9ca229442c8738135b5015450d56e2c1ae07c0aaa93b7da9fe09c2b0

docker_key: 58118E89F3A912897C070ADBF76221572C52609D
docker_keyserver: "hkp://p80.pool.sks-keyservers.net:80"
docker_apt_url: "https://apt.dockerproject.org/repo"
docker_linux_distro: "ubuntu-xenial"

docker:
  start: false
  service_enabled: no

