---

compose_version: "1.20.1"
compose_base_url: "https://github.com/docker/compose/releases/download"

docker_key: 58118E89F3A912897C070ADBF76221572C52609D
docker_keyserver: "hkp://p80.pool.sks-keyservers.net:80"
docker_apt_url: "https://apt.dockerproject.org/repo"
docker_linux_distro: "ubuntu-xenial"

docker:
  start: false
  service_enabled: no

