---

- name: Pull Docker Images
  docker_image:
    name: "{{ item }}"
  with_items: "{{ docker_images }}"
  # register: image_pull

- name: Append Images to PATH
  template:
    src: script.sh.j2
    dest: "/usr/local/bin/{{ item.name }}"
    owner: root
    group: root
    mode: "u=rwx,go=rx"
  with_items: "{{ script_options }}"
  # when: image_pull is changed

- name: Rehash Scripts
  become: false
  ignore_errors: yes
  command: "{{ item }}"
  with_items:
    - "rehash"
    - "hash -r"
