---

maven_version: '3.5.3'
maven_url: 'http://archive.apache.org/dist/maven/maven'
maven_mirror: "{{ maven_url }}-{{ maven_version|regex_replace('\\..*', '') }}/{{ maven_version }}/binaries"

maven_install_dir: /opt/maven

maven_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"

# If this is the default installation, symbolic links to mvn and mvnDebug will
# be created in /usr/local/bin
maven_is_default_installation: yes

# Name of the group of Ansible facts relating this Maven installation.
#
# Override if you want use this role more than once to install multiple versions
# of Maven.
#
# e.g. maven_fact_group_name: maven_3_3
# would change the Maven home fact to:
# ansible_local.maven_3_2.general.home
maven_fact_group_name: maven
