---

- name: Download and Install Minikube
  get_url:
    url: "{{ minikube_base_url }}/{{ minikube_version }}/minikube-linux-amd64"
    dest: "/usr/local/bin/minikube"
    checksum: "sha256:{{ minikube_checksum }}"
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
