---

- name: Install SmartGit
  apt:
    deb: https://www.syntevo.com/downloads/smartgit/smartgit-{{ smartgit_version }}.deb
  register: smartgit_install

- name: Set SmartGit launcher icon
  become: false
  raw: python launcher_add.py syntevo-smartgit.desktop 3
  when: smartgit_install is changed
