---

essential_pkgs:
  - afuse
  - aptitude
  - axel
  - build-essential
  - bzip2
  - ca-certificates
  - colortest
  - curl
  - dbus
  - diffutils
  - dkms
  - dos2unix
  - fdupes
  - findutils
  - ftp-ssl
  - gawk
  - gcc
  - gimp
  - gnash
  - gnome-panel
  - grep
  - gsmartcontrol
  - gufw
  - gzip
  - htop
  - httping
  - iftop
  - imagemagick
  - inotify-tools
  - iotop
  - kdenlive
  - less
  - lftp
  - libsdl-ttf2.0-0
  - libsdl1.2debian
  - make
  - meld
  - nano
  - nfs-common
  - nmap
  - ntp
  - openconnect
  - openssl
  - p7zip
  - pv
  - pwgen
  - python
  - python-dbus
  - python-dev
  - python-pip
  - python3-apt
  - ranger
  - rar
  - rsync
  - samba
  - sed
  - shutter
  - smartmontools
  - smbclient
  - software-properties-common
  - sshfs
  - sshpass
  - swapspace
  - tar
  - tesseract-ocr
  - tig
  - tmux
  - trash-cli
  - ttf-mscorefonts-installer
  - ufw
  - unzip
  - vim
  - vlc
  - vpnc
  - wget
  - whois
  - xmlstarlet
  - xournal
  - youtube-dl
  - zip
