---

- name: Import GPG signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    id: "{{ apt_id }}"

- name: Add repository
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-{{ linux_release }} main'
    state: present

- name: Install Kubectl
  apt:
    pkg: kubectl
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
