---

- name: Download Kubectl into your PATH
  get_url:
    url: "{{ kubectl_base_url }}/{{ kubectl_version }}/bin/linux/{{ kubectl_platform }}/kubectl"
    dest: "{{ kubectl_dest }}"
  register: kubectl

- name: Make Kubectl binary executable
  raw: chmod +x {{ kubectl_dest }}
  when: kubectl is changed
