---

- name: Ensure that Aptitude repositories are up to date
  apt: update_cache=yes cache_valid_time={{ aptcachetime }}

- name: Ensure git is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ git_packages }}"

- name: Ensure gitconfig file for users exists
  copy:
    content: ""
    dest: "/home/{{ ansible_env.USER }}/.gitconfig"
    force: no
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: Ensure git is configured for {{ ansible_env.USER }}
  template:
    src: git-config.j2
    dest: "/home/{{ ansible_env.USER }}/.gitconfig"
    mode: 0644

- name: Get configuration from all scopes
  command: cat /home/{{ ansible_env.USER }}/.gitconfig
  register: cat

- debug: var=cat.stdout_lines
