---

- name: Add Atom repository (Webupd8team)
  apt_repository:
    repo: "ppa:webupd8team/atom"
    state: present

- name: Install Atom text editor
  apt:
    name: atom
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  register: atom_install

- name: Set Atom launcher icon
  become: false
  raw: python launcher_add.py atom.desktop 3
  # when: atom_install is succeeded

- name: Setup Atom Packages
  apm:
    name: sync-settings # All other packages are managed by sync-settings
  become_user: "{{ ansible_env.USER }}"
