---

- name: Add Simple Screen Recorder repository
  apt_repository:
    repo: 'ppa:maarten-baert/simplescreenrecorder'
    state: present

- name: Install Simple Screen Recorder
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  with_items:
    - simplescreenrecorder
    - simplescreenrecorder-lib
  register: ssr_install
