---

helm_version: "v2.9.1"
helm_base_url: "http://storage.googleapis.com/kubernetes-helm"
helm_download_dir: "{{ ansible_env.HOME }}/.helm/archives"
helm_staging_dir: "{{ ansible_env.HOME }}/.helm/{{ helm_version }}"
