---

- name: Import Virtualbox GPG apt signing key
  apt_key:
    id: "{{ vbox_pkg_gpg_key }}"
    url: "{{ vbox_pkg_gpg_url }}"
    state: present

- name: Add Virtualbox apt repository
  apt_repository:
    repo: 'deb {{ vbox_pkg_repo_url }} {{ ansible_distribution_release }} contrib'
    state: present

- name: Install VirtualBox {{ vbox_version }}
  apt:
    pkg: virtualbox-{{ vbox_pkg_apt_version }}
    state: present
  register: vbox_install

- name: Set Virtualbox launcher icon
  become: false
  raw: python launcher_add.py virtualbox.desktop 3
  # when: vbox_install is succeeded

- name: Download Virtualbox Extension pack
  get_url:
    url: "{{ vbox_extpack_url }}"
    dest: "{{ vbox_extpack_dest_path }}"
    checksum: "sha256:{{ vbox_extpack_sha256 }}"
    mode: 0664

- name: Configure Virtualbox post-install drivers
  command: "{{ item }}"
  with_items: "{{ vbox_post_install }}"
  notify:
    - Restart Virtualbox

- name: Do some cleanup
  file:
    name: "{{ tempdir.stdout }}"
    state: absent
