---

- name: Import Virtualbox GPG apt signing key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: Add Virtualbox apt repository
  apt_repository:
    id: '7B0FAB3A13B907435925D9C954422A4B98AB5139'
    repo: 'deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    state: present

- name: Install VirtualBox {{ virtualbox.version }}
  apt:
    pkg: virtualbox-{{ virtualbox.version }}
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  register: vbox_install

- name: Set Virtualbox launcher icon
  become: false
  raw: python launcher_add.py virtualbox.desktop 3
  # when: vbox_install is succeeded
