---

rambox_version_old: "null"
rambox_version_new: "0.5.16"
rambox_filename_new: "Rambox_{{ rambox_version_new }}-x64.deb"
rambox_filename_old: "Rambox_{{ rambox_version_old }}-x64.deb"
rambox_base_url: "https://github.com/saenzramiro/rambox/releases/download"
rambox_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"
rambox_download_timeout_seconds: 1200
rambox_sha256sum: 5a12d6da3643a537b6a598a24dfa93f23f3f3ddcd68a7e4247f92e8966dee4e6
