---

- name: Ensure Gnome Terminal Profile ID
  become: false
  raw: UUID=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
  register: set_uuid 

- name: Disable system fonts and enable custom font
  become: false
  raw: gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${UUID}/ use-system-font false
  register: enable_custom_font
  when: set_uuid|succeeded 

- name: Set custom font
  become: false
  raw: gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${UUID}/ font 'Meslo LG S for Powerline Regular 14'
  when: enable_custom_font|succeeded 
