---

- name: Ensure Curl is present
  apt:
    name: curl
    state: present

- name: Ensure linux-image-extra-* packages are present
  apt:
    name: linux-image-extra-virtual
    state: present

- name: Ensure apt-transport-https is present
  apt:
    name: apt-transport-https
    state: present

- name: Ensure ca-certificates is present
  apt:
    name: ca-certificates
    state: present

#- name: Add Docker’s official GPG key
#  apt_key:
#    keyserver: "{{ docker_keyserver }}"
#    id: "{{ docker_key }}"
#
#- name: Add Docker stable repository
#  apt_repository:
#    repo: deb {{ docker_apt_url }} {{ docker_linux_distro }} main
#    state: present

- name: Import Docker GPG signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 0EBFCD88

- name: Add Docker x86_64 repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
    state: present
  when: ansible_architecture == 'x86_64'

- name: Remove old repo lxc-docker
  apt:
    name: lxc-docker
    state: absent

- name: Install latest version of Docker CE
  apt:
    name: docker-ce
    state: latest
    force: yes
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"

- name: Allow {{ ansible_env.USER }} to use Docker as a non-root user
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Specify a DNS server for use by Docker
  lineinfile:
    dest: /etc/default/docker
    regexp: '^DOCKER_OPTS="--dns'
    line: 'DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"'
  register: docker_install
  notify:
    - Restart Docker service

- name: Ensure Docker Compose is present
  get_url:
    url: "{{ compose_base_url }}/{{ compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    sha256sum: "{{ compose_sha256 }}"

- name: Ensure Docker Compose permissions are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755

- name: Install Docker-py
  raw: pip install --upgrade pip; pip install docker[tls]
