---

- name: Import GnuCash GPG signing key
  apt_key:
    url: http://archive.getdeb.net/getdeb-archive.key
    state: present
    id: 46D7E7CF

- name: Add GnuCash repository
  apt_repository:
    repo: 'deb http://archive.getdeb.net/ubuntu xenial-getdeb apps'
    state: present

- name: Install GnuCash
  apt:
    pkg: gnucash
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  register: cash_install

- name: Remove getdeb - gnucash repository to avoid updating other packages
  apt_repository:
    repo: 'deb http://archive.getdeb.net/ubuntu xenial-getdeb apps'
    state: absent
